version: "3.8"
services:
  promtail:
    image: grafana/promtail:2.9.0
    ports:
      - "9080:9080"
    volumes:
      - airflow_logs:/opt/airflow/logs
      - ./promtail-config.yaml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - default

volumes:
  airflow_logs:
    external: true 
    name: airflow_airflow_logs

networks:
  default:
    external: true
    name: observability-net
