server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_url:3100/loki/api/v1/push

scrape_configs:
  - job_name: airflow-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: minio
          __path__: /opt/airflow/logs/**/*.log
